name: cradle_hr
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - bottleneck=1.3.5=py39h7deecbd_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - cfgv=3.3.1=pyhd8ed1ab_0
  - distlib=0.3.2=pyhd3eb1b0_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - identify=2.5.11=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.20=h043d6bf_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - nodeenv=1.7.0=pyhd8ed1ab_0
  - numexpr=2.8.3=py39hd2a5715_0
  - numpy=1.23.1=py39hf838250_0
  - numpy-base=1.23.1=py39h1e6e340_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py39h6a678d5_0
  - pip=22.1.2=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - pre-commit=2.20.0=py39hf3d152e_1
  - py=1.11.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pytest=7.1.2=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=py39h06a4308_0
  - pyyaml=6.0=py39h7f8727e_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - tzdata=2022a=hda174b7_0
  - ukkonen=1.0.1=py39hf939315_2
  - virtualenv=20.4.6=py39h06a4308_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - albumentations==1.3.0
    - charset-normalizer==2.1.1
    - coloredlogs==15.0.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - cython==0.29.32
    - easydict==1.10
    - flatbuffers==22.12.6
    - fonttools==4.38.0
    - humanfriendly==10.0
    - idna==3.4
    - imageio==2.23.0
    - insightface==0.7.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - matplotlib==3.6.2
    - mpmath==1.2.1
    - networkx==2.8.8
    - onnx==1.13.0
    - onnxruntime==1.13.1
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - pillow==9.3.0
    - prettytable==3.5.0
    - protobuf==3.20.3
    - pywavelets==1.4.1
    - qudida==0.0.4
    - requests==2.28.1
    - scikit-image==0.19.3
    - scikit-learn==1.2.0
    - scipy==1.9.3
    - sympy==1.11.1
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - urllib3==1.26.13
    - wcwidth==0.2.5
